In [1]:
import GNB
import numpy as np
from sklearn import cross_validation as cv
from sklearn import datasets

/Users/user/anaconda/lib/python3.4/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


## create data

In [2]:
data=np.array([
     [-7.82,-4.58,-3.97],
     [-6.72,3.16,2.71],
     [4.36,-2.19,2.09],
     [6.72,0.88,2.80],
     [-8.64,3.06,3.50],
     [-6.87,0.57,-5.45],
     [4.47,-2.62,5.76],
     [6.73,-2.01,4.18],
     [-7.71,2.34,-6.33],
     [-6.91,-0.49,-5.68],
     [6.18,2.81,5.82],
     [6.72,-0.93,-4.04],
     [-6.25,-0.26,0.56],
     [-6.94,-1.22,1.13],
     [8.09,0.20,2.25],
     [6.81,0.17,-4.15],
     [-5.19,4.24,4.04],
     [-6.38,-1.74,1.43],
     [4.08,1.30,5.33],
     [6.27,0.93,-2.78]])

c1_idx=[0, 1, 4, 5, 8, 9, 12, 13, 16, 17]
c2_idx=[2, 3, 6, 7, 10, 11, 14, 15, 18, 19]

ns, nd=data.shape

label=np.array([0 if i in c1_idx else 1 for i in range(ns)])
d_tr_d,d_te_d,d_tr_l,d_te_l = cv.train_test_split(data,label,test_size=0.5,random_state=0)
d_tr_d.shape
print(len(d_tr_d[d_tr_l==0]),len(d_tr_d[d_tr_l==1]))


data=datasets.load_iris().data
target=datasets.load_iris().target

tr_d,te_d,tr_l,te_l = cv.train_test_split(data, target, test_size=0.5, random_state=65)
len(tr_d[tr_l==0]),len(tr_d[tr_l==1]),len(tr_d[tr_l==2])

5 5


(25, 25, 25)

# Performance

In [4]:
model=GNB.GNB()

In [5]:
model.fit(d_tr_d,d_tr_l)

In [6]:
model.predict(d_te_d)

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1])

In [7]:
model.scorering(d_te_l)

1.0

In [8]:
model=GNB.GNB()

In [9]:
model.fit(tr_d,tr_l)

In [10]:
model.predict(te_d)

array([2, 1, 0, 1, 0, 2, 0, 0, 2, 1, 0, 1, 2, 0, 0, 0, 1, 1, 2, 1, 2, 2, 2,
       2, 0, 2, 0, 2, 1, 0, 1, 2, 0, 1, 1, 1, 2, 0, 2, 2, 0, 0, 1, 2, 0, 2,
       2, 2, 0, 0, 1, 1, 0, 2, 1, 1, 1, 1, 2, 0, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       0, 0, 1, 0, 2, 1])

In [11]:
model.scorering(te_l)

0.92

## compete sklearn Bayes model

In [12]:
from sklearn import naive_bayes as nb

In [13]:
sk_model = nb.GaussianNB()

In [14]:
sk_model.fit(d_tr_d, d_tr_l)

GaussianNB(priors=None)

In [15]:
sk_model.predict(d_te_d)

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1])

In [16]:
sk_model.score(d_te_d,d_te_l)

1.0

In [17]:
sk_model = nb.GaussianNB()

In [18]:
sk_model.fit(tr_d, tr_l)

GaussianNB(priors=None)

In [19]:
sk_model.predict(te_d)

array([2, 1, 0, 1, 0, 2, 0, 0, 2, 1, 0, 1, 2, 0, 0, 0, 1, 1, 2, 1, 2, 2, 2,
       2, 0, 2, 0, 2, 1, 0, 1, 2, 0, 1, 1, 1, 2, 0, 2, 2, 0, 0, 1, 2, 0, 2,
       2, 2, 0, 0, 1, 1, 0, 2, 1, 1, 1, 1, 2, 0, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       0, 0, 1, 0, 2, 1])

In [20]:
sk_model.score(te_d,te_l)

0.92000000000000004

In [21]:
def my_NB(X_train, y_train, X_test, y_test):
    model=GNB.GNB()
    model.fit(X_train, y_train)
    model.predict(X_test)
    return model.scorering(y_test)

In [22]:
def sk_NB(X_train, y_train, X_test, y_test):
    sk_model = nb.GaussianNB()
    sk_model.fit(X_train, y_train)
    sk_model.predict(X_test)
    return sk_model.score(X_test, y_test)

In [33]:
%timeit my_NB(tr_d, tr_l, te_d, te_l)

1000 loops, best of 3: 337 µs per loop


In [34]:
%timeit sk_NB(tr_d, tr_l, te_d, te_l)

1000 loops, best of 3: 948 µs per loop


### But

In [35]:
data=datasets.load_digits().data
target=datasets.load_digits().target

dig_tr_d, dig_te_d, dig_tr_l, dig_te_l = cv.train_test_split(data, target, test_size=0.5, random_state=2)

In [38]:
%timeit my_NB(dig_tr_d, dig_tr_l, dig_te_d, dig_te_l)

10 loops, best of 3: 26.1 ms per loop


In [41]:
my_NB(dig_tr_d, dig_tr_l, dig_te_d, dig_te_l)

0.6518353726362626

In [39]:
%timeit sk_NB(dig_tr_d, dig_tr_l, dig_te_d, dig_te_l)

100 loops, best of 3: 9.81 ms per loop


In [40]:
sk_NB(dig_tr_d, dig_tr_l, dig_te_d, dig_te_l)

0.85650723025583986

### I think
##### I using Gaussian distribution 
##### if digit data done not follow Gaussian distribution